### ISSUE TITLE
UE4 build error on windows server container

### ISSUE THREAD

**Issue by zhongjixiuxing** [adamrehn/ue4-cloud-rendering-demo#2]
## [ENV]
    Operating system: Windows Server Datacenter 2019
    Docker image: adamrehn/ue4-full:4.21.1
  
## [INFO]
    I run `ue4 build` step base on ue4-cloud-rendering-demo/project/Dockerfile, got the follow error

```
ERROR: Unable to instantiate module 'UE4Capture': System.IO.FileNotFoundException: Could not find file 'C:\tmp\StreamingDemo\Plugins\UE4Capture\conanbuildinfo.json'.
       File name: 'C:\tmp\StreamingDemo\Plugins\UE4Capture\conanbuildinfo.json'
          at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
          at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean c
heckHost)
          at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
          at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
          at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
          at Tools.DotNETCommon.JsonObject.Read(FileReference File)
          at UE4Capture.ProcessDependencies(String depsJson, ReadOnlyTargetRules target) in c:\tmp\StreamingDemo\Plugins\UE4Capture\Source\UE4Capture\UE4Capture.Build.cs:line 24
       (referenced via default plugins -> UE4Capture.uplugin)
       (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
```

**Comment by adamrehn** [comment]
As stated in the [Prerequisities section of the README](https://github.com/adamrehn/ue4-cloud-rendering-demo#prerequisites), this repository requires NVIDIA Docker, which is only compatible with Linux containers running under a Linux host system. It is not compatible with Windows containers.
